# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Eka Prasasti
profile_img: http://developer.erabelajar.com/content/images/2016/10/picpro.jpg
profile: Chief Technology Officer of Era Belajar (PT Ridaka Indonesia Cerdas). Leads IT team about vision technology in Era Belajar.
social:
  github: 
  facebook:
  twitter:
  instagram:
  linkedin:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
