# Site settings
title: Eka Prasasti - Web Developer
description: "A blog about mind of Eka Prasasti ..."
baseurl: "" # the subpath of your site
url: "https://ekaprasasti.com"

# User settings
username: Eka Prasasti
user_title: Web Developer
email: ekaputraprasasti@gmail.com
facebook_username: ekaprasasti
twitter_username: ekaprasasti
github_username:  ekaprasasti
gplus_username:  +Ekaprasasti90
disqus_username: ekaprasasti
instagram_username: eka_prasasti

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  # - title: about me
  #   url: https://about.me/ekaprasasti
    # url: /about
# projects in header index
projects:
  - name: Era Belajar
    url: http://erabelajar.com
  - name: Developer Era Belajar
    url: http://developer.erabelajar.com
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

future: true
